#ifndef _MACROS_H_
#define _MACROS_H_
//BIT BASED  MACROS
#define SETBIT(WORD,POS) (WORD |=  1<<POS)
#define CLRBIT(WORD,POS) (WORD &= ~(1<<POS))
#define G_SETBIT(WORD,POS) (WORD = 1<<POS)
#define RBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
//BYTE MACROS
#define WBYTE(WORD,POS,DATA) (WORD = (WORD&~(255<<POS))|(DATA<<POS))
//NIBBLE MACROS
#define WNIBBLE(WORD,POS,DATA) (WORD =(WORD&~(15<<POS))|(DATA<<POS))
#define RNIBBLE(WORD,POS) ((WORD>>POS)&15)
#endif
